# -*- coding: utf-8 -*-
"""Advance_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbabSgqkzTgiKRysBhSmzOppk8p3TTJg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

iris = pd.read_csv('/content/drive/MyDrive/Data_sets/iris.csv')
iris

iris['Species'] = iris['Species'].replace({'Iris-setosa':0,'Iris-versicolor':1,"Iris-virginica":2})
iris.sample(5)

plt.scatter(iris['SepalLengthCm'],iris['PetalLengthCm'],c=iris['Species'],cmap='jet',alpha=0.7)
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalLengthCm')
plt.title('sepal length vs petal length')
plt.colorbar()

plt.figure(figsize=(5,4))
plt.scatter(iris['SepalLengthCm'],iris['PetalLengthCm'],c=iris['Species'],cmap='jet',alpha=0.7)
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalLengthCm')
plt.title('sepal length vs petal length')
plt.colorbar()

batters = pd.read_csv('/content/drive/MyDrive/Data_sets/batter.csv')
batters.head(5)
#

sample_df = batters.head(100).sample(25,random_state=5)
sample_df

plt.figure(figsize=(18,10))
plt.scatter(sample_df['avg'],sample_df['strike_rate'],s=sample_df['runs'])

plt.axhline(y=140,color='red',linestyle='--')
plt.axvline(x=30,color='black',linestyle='--')

for i in range(sample_df.shape[0]):
  plt.text(sample_df['avg'].values[i],sample_df['strike_rate'].values[i],sample_df['batter'].values[i])

x = [1,2,3,4]
y = [5,6,7,8]
plt.scatter(x,y)
plt.text(1,5,'point 1')
plt.text(2,6,'point 2')
plt.text(3,7,'point 3')
plt.text(4,8,'point 4',fontdict={'size':12,'color':'red'})

"""## Sub-plots


"""

batters.head()

plt.scatter(batters['avg'],batters['strike_rate'])

fig, ax = plt.subplots(figsize=(10,6))
ax.scatter(batters['avg'],batters['strike_rate'],color ='red',marker='+')
ax.set_title("avg vs strike rate")
ax.set_xlabel("avg")
ax.set_ylabel("strike_rate")
fig.show()

from matplotlib import markers
fig, ax = plt.subplots(nrows=2,ncols=1,figsize=(10,6),sharex=True)
ax[0].scatter(batters['avg'],batters['strike_rate'],color = 'red', marker = '+')
ax[1].scatter(batters['avg'],batters['runs'],color = 'black', marker = '*')
ax[0].set_title("avg vs strike rate")
ax[1].set_title("avg vs runs")
ax[0].set_xlabel("avg")
ax[1].set_xlabel("avg")
ax[0].set_ylabel("strike_rate")
ax[1].set_ylabel("runs")
fig.show()

fig = plt.figure()
ax1 = fig.add_subplot(1,2,1)
ax1.scatter(batters['avg'],batters['strike_rate'],color = 'red', marker = '+')
ax1 = fig.add_subplot(1,2,2)
ax1.scatter(batters['avg'],batters['runs'],color = 'black', marker = '*')