# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdmu9YmDYbM9uRU6lFPqmmj4Y9A0eRW-

## Types of Data


*   Numerical Data
*   Categorical Data
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# 2d plot - Bivariate Analysis , numerical col & categorical col , Time Series data

# ploting a simple fuctions
price = [45000, 55000, 89000, 55000,90000,70000]
year = [2015, 2016, 2017, 2018, 2019 , 2020]
plt.plot(year,price)

from google.colab import drive
drive.mount('/content/drive')
batsman = pd.read_csv('/content/drive/MyDrive/Data_sets/sharma-kohli.csv')
batsman
plt.plot(batsman['index'],batsman['V Kohli'])
plt.plot(batsman['index'],batsman['RG Sharma'])

plt.plot(batsman['index'],batsman['V Kohli'])
plt.plot(batsman['index'],batsman['RG Sharma'])
plt.title("comparison between Virat Kohli & RG Sharma")
plt.xlabel("Year")
plt.ylabel("Runs")

plt.plot(batsman['index'],batsman['V Kohli'],color = 'red',linestyle ='solid',linewidth=3,marker ='D',markersize = 5)
plt.plot(batsman['index'],batsman['RG Sharma'],color = 'black', linestyle="dashdot", linewidth=2,marker='o')
plt.title("comparison between Virat Kohli & RG Sharma")
plt.xlabel("Year")
plt.ylabel("Runs")

#legend -> location
plt.plot(batsman['index'],batsman['V Kohli'],color = 'red',linestyle ='solid',linewidth=3,marker ='D',markersize = 5,label = 'virat')
plt.plot(batsman['index'],batsman['RG Sharma'],color = 'black', linestyle="dashdot", linewidth=2,marker='o',label ='Rohit')
plt.title("comparison between Virat Kohli & RG Sharma")
plt.xlabel("Year")
plt.ylabel("Runs")
plt.legend(loc = 'best')

price = [45000, 55000, 89000, 55000,90000,7000000]
year = [2015, 2016, 2017, 2018, 2019 , 2020]
plt.plot(year,price)
plt.ylim(0,750000)
plt.xlim(2015,2020)

#grid
plt.plot(batsman['index'],batsman['V Kohli'],color = 'red',linestyle ='solid',linewidth=3,marker ='D',markersize = 5,label = 'virat')
plt.plot(batsman['index'],batsman['RG Sharma'],color = 'black', linestyle="dashdot", linewidth=2,marker='o',label ='Rohit')
plt.title("comparison between Virat Kohli & RG Sharma")
plt.xlabel("Year")
plt.ylabel("Runs")
plt.legend(loc = 'best')
plt.grid()

#show
plt.plot(batsman['index'],batsman['V Kohli'],color = 'red',linestyle ='solid',linewidth=3,marker ='D',markersize = 5,label = 'virat')
plt.plot(batsman['index'],batsman['RG Sharma'],color = 'black', linestyle="dashdot", linewidth=2,marker='o',label ='Rohit')
plt.title("comparison between Virat Kohli & RG Sharma")
plt.xlabel("Year")
plt.ylabel("Runs")
plt.legend(loc = 'best')
plt.grid()
plt.show()

"""## Scatter Plots


*   Bivariate Analysis
*   Numerical vs Numerical
*   use case - Find Correlation
"""

#plt.scatter simple function
x = np.linspace(-10,10,50)
y = 10*x +3+np.random.randint(0,300,50)
y

plt.scatter(x,y)

#plt.scatter on pandas data
df = pd.read_csv('/content/drive/MyDrive/Data_sets/batter.csv')
df.head(50)

plt.scatter(df['avg'],df['strike_rate'],color ='green',marker= "+")
plt.title('Scatter Plot')
plt.xlabel('avg')
plt.ylabel('strike_rate')

#size
tips = sns.load_dataset('tips')
#slower
plt.scatter(tips['total_bill'],tips["tip"],s=tips['size']*20)

#Scattering using plt.plot
#faster
plt.plot(tips['total_bill'],tips['tip'],'o')

"""## Bar Chart

*   Bivariate Analysis
*   Numerical Categorical
*   use case - Aggregate Analysis of Groups





"""

#simple Bar Chart
children = [10,20,30,40]
colors = ["red","green","blue","yellow"]
plt.bar(colors,children,color = 'hotpink')
plt.xlabel("Colors")
plt.ylabel("Children")
plt.title("Children Likes Colors")

#horizontal bar chart
children = [10,20,30,40]
colors = ["red","green","blue","yellow"]
plt.xlabel("CHILDREN")
plt.ylabel("COLORS")
plt.title("Children Likes Colors")
plt.barh(colors,children,color = 'hotpink')

#COLORS & LABEL
df = pd.read_csv('/content/drive/MyDrive/Data_sets/batsman_season_record.csv')
df

plt.bar(np.arange(df.shape[0])-0.2,df['2015'],width=0.2,color ='Black')
plt.bar(np.arange(df.shape[0]),df['2016'],width=0.2,color = 'Red')
plt.bar(np.arange(df.shape[0])+0.2,df['2017'],width=0.2,color = 'Grey')
plt.xticks(np.arange(df.shape[0]),df['batsman'])
plt.show()

children = [10,20,30,40]
colors = ["red red red red red","green green green green green ","blue blue blue blue ","yellow yellow yellow yellow"]
plt.bar(colors,children,color = 'hotpink')
plt.xlabel("Colors")
plt.ylabel("Children")
plt.title("Children Likes Colors")
plt.xticks(rotation ='vertical')

#Stacked Bar Chart
plt.bar(df['batsman'],df['2015'],color = "red",label = '2015')
plt.bar(df['batsman'],df['2016'],bottom=df['2015'],color ='black',label = '2016')
plt.bar(df['batsman'],df['2017'],bottom=df['2016']+ df['2015'],color = 'yellow',label = '2017')
plt.xticks(rotation=50)
plt.legend()
plt.show()

"""## Histogram

*   Univariate Analysis
*   Numerical col
*   use case - Frequency count
"""

data = [36, 56,45,16,28,61]
plt.hist(data, bins = [10,20,30,40,50,70])

df = pd.read_csv('/content/drive/MyDrive/Data_sets/vk.csv')
df

plt.hist(df['batsman_runs'],bins=[0,10,20,30,40,50,60,70,80])
plt.show()

#handling bins

#logarithmic Scale
arr = np.load('/content/drive/MyDrive/Data_sets/big-array.npy')
plt.hist(arr,bins =[10,20,30,40,50,60,70],log='True')
plt.show()

"""## Pie Chart

*   Univariate/Bivariate Analysis
*   Categorical vs Numerical
*   Use Case - To find Contribution on a standard scale





"""

data = [23,45,100,20,49]
subjects = ['Maths','Physics','Chemistry','Biology','English']
plt.pie(data, labels = subjects)
plt.show()

df = pd.read_csv('/content/drive/MyDrive/Data_sets/gayle-175.csv')
df

plt.pie(df['batsman_runs'], labels = df['batsman'],autopct='%0.1f%%',colors=['blue', 'hotpink',"yellow",'red','cyan','brown'],explode =[0.1,0,0,0,0,0],shadow=True)
plt.show()

plt.style.available

plt.style.use('dark_background')

arr = np.load('/content/drive/MyDrive/Data_sets/big-array.npy')
plt.hist(arr,bins =[10,20,30,40,50,60,70],log='True')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

arr = np.load('/content/drive/MyDrive/Data_sets/big-array.npy')
plt.hist(arr,bins =[10,20,30,40,50,60,70],log='True')
plt.savefig('sample.png')